# Generated by Django 5.2.9 on 2025-12-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderitem_color_orderitem_size_orderitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='productsizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_shoe_size', models.CharField(help_text='sizes eg ehither S M L XL or 38 40 42', max_length=50)),
                ('hips', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, help_text='height of shoeor trouser or  dress', max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_colors', to='products.productsizes')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
