# Generated by Django 5.2.9 on 2025-12-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.mainoffer'),
        ),
    ]
