# Generated by Django 5.2.9 on 2025-12-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mainoffer_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
    ]
