# Generated by Django 5.2.9 on 2025-12-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_offer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainoffer',
            name='is_active',
        ),
    ]
