# Generated by Django 5.2.9 on 2026-01-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_mainoffer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
