# Generated by Django 5.2.9 on 2026-01-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
    ]
