# Generated by Django 5.2.9 on 2026-01-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_offer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
